### ISSUE TITLE
add tags for implementation

### ISSUE THREAD

**Issue by mklinik** [clean-cloogle/cloogle-tags#3]
Currently, tags for exported functions are only generated for the .dcl file. When developing software, I most often want to jump to the implementation instead.

Can you add a flag that also generates tags for the implementation?

**Comment by camilstaps** [comment]
With `-c`, comments are added; the comment `icl` contains the line in the implementation where the things is defined (if it exists in the icl). For example:

```
!!	/opt/clean/lib/StdEnv/StdList.dcl	33;"	thing:function	module:StdList	icl:84
```

With `-l`, also toplevel not-exported definitions are indexed.

I recently added [a series of commands](https://github.com/camilstaps/vim-clean/blob/master/doc/clean.txt#L86) to [vim-clean](https://github.com/camilstaps/vim-clean) to jump to definition/implementation: `<LocalLeader>it` for instance jumps to the implementation in a new tab.

Does that answer your question?

**Comment by mklinik** [comment]
Yup, works for me. Thanks!
